Fix error lines for GLSL output (#7207)
glslang outputs its message strangely (and it is not going to change,
otherwise I would have made the changes there)

This will take an ouptut like

```
ERROR: <source>:4: Something bad
WARNING: <source>:5: Something less bad
```

to be

```
<source>:4: Something bad
<source>:5: warning: Something less bad
```

so it appears automatically in the UI


![image](https://github.com/user-attachments/assets/05454b10-abf7-4f81-8f26-17970028f3f8)